### ISSUE TITLE
ENOENT: no such file or directory when running npx create-uix-app

### ISSUE THREAD

**Issue by danielmartincraig** [pitch-io/uix#113]
**Describe the bug**

When I run `npx create-uix-app daniel/test-app`, I see ENOENT: no such file or directory

**Include minimal repro**
```
daniel@Mac Repos % npx create-uix-app daniel/test-app
Downloading project template from https://github.com/pitch-io/uix-starter...
node:internal/fs/utils:346
    throw err;
    ^

Error: ENOENT: no such file or directory, rename '/Users/daniel/Repos/uix-starter-main' -> '/Users/daniel/Repos/daniel/test-app'
    at Object.renameSync (node:fs:1025:3)
    at Unpack.<anonymous> (/Users/daniel/.npm/_npx/520f0c1868eef90e/node_modules/create-uix-app/src/index.js:46:18)
    at Unpack.emit (node:events:524:35)
    at [maybeClose] (/Users/daniel/.npm/_npx/520f0c1868eef90e/node_modules/tar/lib/unpack.js:236:12)
    at [unpend] (/Users/daniel/.npm/_npx/520f0c1868eef90e/node_modules/tar/lib/unpack.js:538:21)
    at /Users/daniel/.npm/_npx/520f0c1868eef90e/node_modules/tar/lib/unpack.js:438:25
    at FSReqCallback.oncomplete (node:fs:180:23) {
  errno: -2,
  syscall: 'rename',
  code: 'ENOENT',
  path: '/Users/daniel/Repos/uix-starter-main',
  dest: '/Users/daniel/Repos/daniel/test-app'
}

Node.js v19.5.0
```

**Expected behavior**

I expected a starter project to be created without error.

**Additional context**

**Comment by roman01la** [comment]
There’s a repo for the starter project, please report your issue there https://github.com/pitch-io/uix-starter
